vuejs.settings:
  type: config_object
  label: Vue.js settings
  mapping:
    libraries:
      type: mapping
      label: Libraries
      mapping:
        vue:
          type: mapping
          label: Vue settings
          mapping:
            installation:
              type: string
              label: Vue installation
            development:
              type: boolean
              label: development
            version:
              type: string
              label: Vue version
